using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TeamPlayCRUD.Helpers
{
    public class CountryCodeGerator
    {
        public static List<String> GetContriesCode()
        {
            string countriesCode = @"AFG
            ALA
            ALB
            DZA
            ASM
            AND
            AGO
            AIA
            ATA
            ATG
            ARG
            ARM
            ABW
            AUS
            AUT
            AZE
            BHS
            BHR
            BGD
            BRB
            BLR
            BEL
            BLZ
            BEN
            BMU
            BTN
            BOL
            BIH
            BWA
            BVT
            BRA
            IOT
            BRN
            BGR
            BFA
            BDI
            KHM
            CMR
            CAN
            CPV
            CYM
            CAF
            TCD
            CHL
            CHN
            CXR
            CCK
            COL
            COM
            COG
            CD
            COK
            CRI
            CIV
            HRV
            CUB
            CYP
            CZE
            DNK
            DJI
            DMA
            DOM
            ECU
            EGY
            SLV
            GNQ
            ERI
            EST
            ETH
            FLK
            FRO
            FJI
            FIN
            FRA
            GUF
            PYF
            ATF
            GAB
            GMB
            GEO
            DEU
            GHA
            GIB
            GRC
            GRL
            GRD
            GLP
            GUM
            GTM
            GGY
            GIN
            GNB
            GUY
            HTI
            HMD
            VAT
            HND
            HKG
            HUN
            ISL
            IND
            IDN
            IRN
            IRQ
            IRL
            IMN
            ISR
            ITA
            JAM
            JPN
            JEY
            JOR
            KAZ
            KEN
            KIR
            KP
            KR
            KWT
            KGZ
            LAO
            LVA
            LBN
            LSO
            LBR
            LBY
            LIE
            LTU
            LUX
            MAC
            MK
            MDG
            MWI
            MYS
            MDV
            MLI
            MLT
            MHL
            MTQ
            MRT
            MUS
            MYT
            MEX
            FM
            MD
            MCO
            MNG
            MNE
            MSR
            MAR
            MOZ
            MMR
            NAM
            NRU
            NPL
            NLD
            ANT
            NCL
            NZL
            NIC
            NER
            NGA
            NIU
            NFK
            MNP
            NOR
            OMN
            PAK
            PLW
            PS
            PAN
            PNG
            PRY
            PER
            PHL
            PCN
            POL
            PRT
            PRI
            QAT
            REU
            ROU
            RUS
            RWA
            BLM
            SH
            KNA
            LCA
            MAF
            SPM
            VCT
            WSM
            SMR
            STP
            SAU
            SEN
            SRB
            SYC
            SLE
            SGP
            SVK
            SVN
            SLB
            SOM
            ZAF
            SGS
            ESP
            LKA
            SDN
            SUR
            SJM
            SWZ
            SWE
            CHE
            SYR
            TWN
            TJK
            TZ
            THA
            TLS
            TGO
            TKL
            TON
            TTO
            TUN
            TUR
            TKM
            TCA
            TUV
            UGA
            UKR
            ARE
            GBR
            USA
            UMI
            URY
            UZB
            VUT
            VEN
            VNM
            VG
            VI
            WLF
            ESH
            YEM
            ZMB
            ZWE
            ";

            List<string> countriesCodeList=  countriesCode
                .TrimEnd().TrimStart()
                .Split("\r\n")
                .Select(x => x.Trim()).ToList();

            return countriesCodeList;
        }
    }
}
